// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itsqltmmzdovcylkgjkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0c3FsdG1temRvdmN5bGtnamtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MDEyMzIsImV4cCI6MjA2NjM3NzIzMn0.rKdWfInzYKlK5Rn_F047Ra2k3ZWlOlg6TnWQxSVyK2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);